export enum PhotosConst {
    GET_LIST_ITEMS_PHTOS_START = 'GET_LIST_ITEMS_PHTOS_START',
    GET_LIST_ITEMS_PHTOS_SUCCESS = 'GET_LIST_ITEMS_PHTOS_SUCCESS',
    GET_LIST_ITEMS_PHTOS_FIALED = 'GET_LIST_ITEMS_PHTOS_FIALED',
    GET_LIST_ITEM_PHTOS_START = 'GET_LIST_ITEMS_PHTO_START',
    GET_LIST_ITEM_PHTOS_SUCCESS = 'GET_LIST_ITEMS_PHTO_SUCCESS',
    GET_LIST_ITEM_PHTOS_FIALED = 'GET_LIST_ITEMS_PHTO_FIALED',

}
